import importlib
import json
import sys
import uuid
from pathlib import Path
from types import SimpleNamespace
import os
import psycopg
import pytest

# Add the src directory to sys.path so pytest can import app.py as "app".
ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

# pyrefly: ignore [missing-import]
import load_data  # noqa: E402

pytestmark = [pytest.mark.db, pytest.mark.integration]

@pytest.fixture
def app_module():
    """Import and return the Flask app module.

    :return: The imported ``app`` module.
    :rtype: module
    """
    return importlib.import_module("app")

@pytest.fixture
def client(app_module):
    original_testing = app_module.app.config.get("TESTING", False)
    original_pull_busy = getattr(app_module, "pull_data_running", False)

    app_module.app.config.update(TESTING=True)
    app_module.pull_data_running = False

    with app_module.app.test_client() as test_client:
        yield test_client

    app_module.app.config.update(TESTING=original_testing)
    app_module.pull_data_running = original_pull_busy
    
@pytest.fixture
def db_connection():
    """Create a live connection to ``applicant_db``.

    :yield: PostgreSQL connection for test setup and verification.
    :rtype: psycopg.Connection
    """
    
    db_url = os.environ.get("DATABASE_URL")
    if db_url:
        connection = psycopg.connect(conninfo=db_url)
    else:
        connection = psycopg.connect(
            dbname="applicant_db",
            user="postgres",
        )
    try:
        yield connection
    finally:
        connection.close()

@pytest.fixture
def test_table_name():
    """Generate a unique test table name.

    Using a unique table per test avoids collisions across runs.

    :return: Unique test table name.
    :rtype: str
    """
    return f"applicants_test_{uuid.uuid4().hex[:10]}"

@pytest.fixture
def managed_test_table(db_connection, test_table_name):
    """Create and later drop an isolated test table.

    The schema mirrors the Module-3 applicants table so ``load_data.py`` can
    insert rows into it during the route test.

    :param db_connection: Live PostgreSQL connection.
    :type db_connection: psycopg.Connection
    :param test_table_name: Unique table name for the test.
    :type test_table_name: str
    :yield: The created table name.
    :rtype: str
    """
    with db_connection.cursor() as cur:
        cur.execute(
            f"""
            CREATE TABLE IF NOT EXISTS {test_table_name} (
                p_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                program text,
                comments text,
                date_added date,
                url text UNIQUE,
                status text,
                term text,
                us_or_international text,
                gpa float,
                gre float,
                gre_v float,
                gre_aw float,
                degree text,
                llm_generated_program text,
                llm_generated_university text,
                loaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
    db_connection.commit()

    try:
        yield test_table_name
    finally:
        with db_connection.cursor() as cur:
            cur.execute(f"DROP TABLE IF EXISTS {test_table_name}")
        db_connection.commit()

def _completed_process(returncode=0, stdout="", stderr=""):
    """Build a fake subprocess result object.

    :param returncode: Simulated process return code.
    :type returncode: int
    :param stdout: Simulated stdout.
    :type stdout: str
    :param stderr: Simulated stderr.
    :type stderr: str
    :return: Object mimicking a subprocess result.
    :rtype: types.SimpleNamespace
    """
    return SimpleNamespace(returncode=returncode, stdout=stdout, stderr=stderr)

def _sample_raw_rows():
    """Return fake scraped raw rows.

    :return: Sample raw applicant rows.
    :rtype: list[dict]
    """
    return [
        {
            "Program Name": "Johns Hopkins University Computer Science",
            "Comments": "Admitted with funding",
            "Date of Information Added to Grad Cafe": "January 15, 2026",
            "URL link to applicant entry": "https://example.com/applicant/1",
            "Applicant Status": "Accepted",
            "Semester and Year of Program Start": "Fall 2026",
            "International / American Student": "American",
            "GPA": "3.91",
            "GRE Score": "325",
            "GRE V Score": "160",
            "GRE AW": "4.5",
            "Masters or PhD": "Masters",
            "llm-generated-program": "Computer Science",
            "llm-generated-university": "Johns Hopkins University",
        },
        {
            "Program Name": "MIT Computer Science",
            "Comments": "Interviewed",
            "Date of Information Added to Grad Cafe": "January 16, 2026",
            "URL link to applicant entry": "https://example.com/applicant/2",
            "Applicant Status": "Accepted",
            "Semester and Year of Program Start": "Fall 2026",
            "International / American Student": "International",
            "GPA": "3.80",
            "GRE Score": "330",
            "GRE V Score": "162",
            "GRE AW": "5.0",
            "Masters or PhD": "PhD",
            "llm-generated-program": "Computer Science",
            "llm-generated-university": "MIT",
        },
    ]

def _load_table_count(connection, table_name):
    """Return the number of rows in a table.

    :param connection: Live PostgreSQL connection.
    :type connection: psycopg.Connection
    :param table_name: Table to count.
    :type table_name: str
    :return: Row count.
    :rtype: int
    """
    with connection.cursor() as cur:
        cur.execute(f"SELECT COUNT(*) FROM {table_name}")
        return cur.fetchone()[0]

def _fetch_first_row_as_dict(connection, table_name):
    """Fetch one inserted row as a dictionary keyed by Module-3 field names.

    :param connection: Live PostgreSQL connection.
    :type connection: psycopg.Connection
    :param table_name: Table to query.
    :type table_name: str
    :return: Row mapped by column name.
    :rtype: dict[str, object] | None
    """
    with connection.cursor() as cur:
        cur.execute(
            f"""
            SELECT
                program,
                comments,
                date_added,
                url,
                status,
                term,
                us_or_international,
                gpa,
                gre,
                gre_v,
                gre_aw,
                degree,
                llm_generated_program,
                llm_generated_university
            FROM {table_name}
            ORDER BY p_id
            LIMIT 1
            """
        )
        row = cur.fetchone()

    if row is None:
        return None

    keys = [
        "program",
        "comments",
        "date_added",
        "url",
        "status",
        "term",
        "us_or_international",
        "gpa",
        "gre",
        "gre_v",
        "gre_aw",
        "degree",
        "llm_generated_program",
        "llm_generated_university",
    ]
    return dict(zip(keys, row))

def test_post_pull_data_inserts_rows_with_required_non_null_fields(
    client,
    app_module,
    monkeypatch,
    db_connection,
    managed_test_table,
):
    """Verify that ``POST /pull-data`` writes rows into PostgreSQL.

    This test uses the live ``applicant_db`` database but redirects inserts to a
    test-specific table. Scrape and clean steps are faked, while the real
    ``load_json_to_postgres`` function performs the insert.

    :param client: Flask test client.
    :type client: flask.testing.FlaskClient
    :param app_module: Imported Flask app module.
    :type app_module: module
    :param monkeypatch: Pytest monkeypatch fixture.
    :type monkeypatch: pytest.MonkeyPatch
    :param db_connection: Live PostgreSQL connection.
    :type db_connection: psycopg.Connection
    :param managed_test_table: Test-only table name.
    :type managed_test_table: str
    :return: None
    :rtype: None
    """

    test_table = managed_test_table
    raw_rows = _sample_raw_rows()

    assert _load_table_count(db_connection, test_table) == 0

    def fake_run_python_script(script_path, *args):
        """Fake scrape/clean and run real load against the test table."""
        script_path = Path(script_path)

        if script_path == app_module.SCRAPE_SCRIPT:
            app_module.RAW_JSON_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
            with open(app_module.RAW_JSON_OUTPUT, "w", encoding="utf-8") as f:
                json.dump(raw_rows, f, indent=2)
            return _completed_process(returncode=0, stdout="scraped")

        if script_path == app_module.CLEAN_SCRIPT:
            input_path = Path(args[0])
            output_path = Path(args[1])

            with open(input_path, "r", encoding="utf-8") as src:
                payload = json.load(src)

            output_path.parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, "w", encoding="utf-8") as dst:
                json.dump(payload, dst, indent=2)

            return _completed_process(returncode=0, stdout="cleaned")

        if script_path == app_module.LOAD_SCRIPT:
            args_list = list(args)
            input_path = args_list[args_list.index("--input") + 1]
            delete_date = None
            if "--delete-date" in args_list:
                delete_date = args_list[args_list.index("--delete-date") + 1]

            load_data.load_json_to_postgres(
                json_file=input_path,
                table_name=test_table,
                delete_date=delete_date,
            )
            return _completed_process(returncode=0, stdout="loaded")

        return _completed_process(returncode=1, stderr="unexpected script call")

    monkeypatch.setattr(app_module, "run_python_script", fake_run_python_script)
    monkeypatch.setattr(app_module, "load_watermark", lambda: None)
    monkeypatch.setattr(app_module, "save_watermark", lambda value: None)

    response = client.post("/pull-data")

    assert response.status_code == 200
    assert response.get_json()["ok"] is True

    assert _load_table_count(db_connection, test_table) == 2

    first_row = _fetch_first_row_as_dict(db_connection, test_table)
    assert first_row is not None

    required_non_null_fields = [
        "program",
        "comments",
        "date_added",
        "url",
        "status",
        "term",
        "us_or_international",
        "degree",
        "llm_generated_program",
        "llm_generated_university",
    ]

    for field_name in required_non_null_fields:
        assert first_row[field_name] is not None
        assert first_row[field_name] != ""

def test_duplicate_pulls_do_not_create_duplicate_rows(
    client,
    app_module,
    monkeypatch,
    db_connection,
    managed_test_table,
):
    """Verify idempotent behavior for repeated pulls of the same dataset.

    This test enforces a uniqueness policy at the test-table level and confirms
    that posting the same pulled data twice does not increase row count.

    :param client: Flask test client.
    :type client: flask.testing.FlaskClient
    :param app_module: Imported Flask app module.
    :type app_module: module
    :param monkeypatch: Pytest monkeypatch fixture.
    :type monkeypatch: pytest.MonkeyPatch
    :param db_connection: Live PostgreSQL connection.
    :type db_connection: psycopg.Connection
    :param managed_test_table: Test-only table name.
    :type managed_test_table: str
    :return: None
    :rtype: None
    """

    test_table = managed_test_table
    raw_rows = _sample_raw_rows()

    # Add a uniqueness policy for the test table based on applicant URL.
    with db_connection.cursor() as cur:
        cur.execute(
            f"""
            CREATE UNIQUE INDEX IF NOT EXISTS {test_table}_url_uniq_idx
            ON {test_table} (url)
            """
        )
    db_connection.commit()

    def fake_run_python_script(script_path, *args):
        """Fake scrape/clean and use real load for the test table."""
        script_path = Path(script_path)

        if script_path == app_module.SCRAPE_SCRIPT:
            with open(app_module.RAW_JSON_OUTPUT, "w", encoding="utf-8") as f:
                json.dump(raw_rows, f, indent=2)
            return _completed_process(returncode=0, stdout="scraped")

        if script_path == app_module.CLEAN_SCRIPT:
            input_path = Path(args[0])
            output_path = Path(args[1])

            with open(input_path, "r", encoding="utf-8") as src:
                payload = json.load(src)

            with open(output_path, "w", encoding="utf-8") as dst:
                json.dump(payload, dst, indent=2)

            return _completed_process(returncode=0, stdout="cleaned")

        if script_path == app_module.LOAD_SCRIPT:
            args_list = list(args)
            input_path = args_list[args_list.index("--input") + 1]
            delete_date = None
            if "--delete-date" in args_list:
                delete_date = args_list[args_list.index("--delete-date") + 1]

            try:
                load_data.load_json_to_postgres(
                    json_file=input_path,
                    table_name=test_table,
                    delete_date=delete_date,
                )
                return _completed_process(returncode=0, stdout="loaded")
            except Exception as exc:
                return _completed_process(returncode=1, stderr=str(exc))

        return _completed_process(returncode=1, stderr="unexpected script call")

    monkeypatch.setattr(app_module, "run_python_script", fake_run_python_script)
    monkeypatch.setattr(app_module, "load_watermark", lambda: None)
    monkeypatch.setattr(app_module, "save_watermark", lambda value: None)

    first_response = client.post("/pull-data")
    first_count = _load_table_count(db_connection, test_table)

    second_response = client.post("/pull-data")
    second_count = _load_table_count(db_connection, test_table)

    assert first_response.status_code == 200
    assert first_count == 2

    # This assertion reflects the assignment requirement.
    # It will pass only if your load policy truly prevents duplicates.
    assert second_response.status_code == 200
    assert second_count == first_count

def test_simple_query_returns_expected_module3_keys(
    db_connection,
    managed_test_table,
):
    """Verify a simple query can return a dict with expected Module-3 keys.

    This test inserts one row directly into the test table, then queries it back
    as a dictionary and checks the key set expected by the analysis layer.

    :param db_connection: Live PostgreSQL connection.
    :type db_connection: psycopg.Connection
    :param managed_test_table: Test-only table name.
    :type managed_test_table: str
    :return: None
    :rtype: None
    """
    test_table = managed_test_table

    with db_connection.cursor() as cur:
        cur.execute(
            f"""
            INSERT INTO {test_table} (
                program,
                comments,
                date_added,
                url,
                status,
                term,
                us_or_international,
                gpa,
                gre,
                gre_v,
                gre_aw,
                degree,
                llm_generated_program,
                llm_generated_university
            )
            VALUES (
                %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
            )
            """,
            (
                "Stanford University Computer Science",
                "Strong profile",
                "2026-01-20",
                "https://example.com/applicant/3",
                "Accepted",
                "Fall 2026",
                "American",
                3.95,
                332.0,
                165.0,
                5.0,
                "PhD",
                "Computer Science",
                "Stanford University",
            ),
        )
    db_connection.commit()

    result = _fetch_first_row_as_dict(db_connection, test_table)

    expected_keys = {
        "program",
        "comments",
        "date_added",
        "url",
        "status",
        "term",
        "us_or_international",
        "gpa",
        "gre",
        "gre_v",
        "gre_aw",
        "degree",
        "llm_generated_program",
        "llm_generated_university",
    }

    assert result is not None
    assert set(result.keys()) == expected_keys
