import importlib
import json
import re
import sys
import uuid
from pathlib import Path
from types import SimpleNamespace
import os
import psycopg
import pytest
from bs4 import BeautifulSoup

# Add the src directory to sys.path so pytest can import app.py and load_data.py.
ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

# pyrefly: ignore [missing-import]
import load_data  # noqa: E402

pytestmark = [pytest.mark.integration, pytest.mark.db, pytest.mark.web]

@pytest.fixture
def app_module():
    """Import and return the Flask app module.

    :return: The imported ``app`` module.
    :rtype: module
    """
    return importlib.import_module("app")

@pytest.fixture
def client(app_module):
    """Create a Flask test client.

    :param app_module: The imported Flask app module.
    :type app_module: module
    :yield: A Flask test client instance.
    :rtype: flask.testing.FlaskClient
    """
    original_testing = app_module.app.config.get("TESTING", False)
    original_pull_busy = getattr(app_module, "pull_data_running", False)

    app_module.app.config.update(TESTING=True)
    app_module.pull_data_running = False

    with app_module.app.test_client() as test_client:
        yield test_client

    app_module.app.config.update(TESTING=original_testing)
    app_module.pull_data_running = original_pull_busy

@pytest.fixture
def db_connection():
    """Create a live connection to ``applicant_db``.

    :yield: PostgreSQL connection used for setup and verification.
    :rtype: psycopg.Connection
    """
    db_url = os.environ.get("DATABASE_URL")
    if db_url:
        connection = psycopg.connect(conninfo=db_url)
    else:
        connection = psycopg.connect(
            dbname="applicant_db",
            user="postgres",
        )
    try:
        yield connection
    finally:
        connection.close()

@pytest.fixture
def test_table_name():
    """Generate a unique integration-test table name.

    :return: Unique table name for the current test.
    :rtype: str
    """
    return f"applicants_integration_{uuid.uuid4().hex[:10]}"

@pytest.fixture
def managed_test_table(db_connection, test_table_name):
    """Create and later drop an isolated test table.

    :param db_connection: Live PostgreSQL connection.
    :type db_connection: psycopg.Connection
    :param test_table_name: Unique table name for the test.
    :type test_table_name: str
    :yield: The created table name.
    :rtype: str
    """
    with db_connection.cursor() as cur:
        cur.execute(
            f"""
            CREATE TABLE IF NOT EXISTS {test_table_name} (
                p_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                program text,
                comments text,
                date_added date,
                url text,
                status text,
                term text,
                us_or_international text,
                gpa float,
                gre float,
                gre_v float,
                gre_aw float,
                degree text,
                llm_generated_program text,
                llm_generated_university text,
                loaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """
        )

        cur.execute(
            f"""
            CREATE UNIQUE INDEX IF NOT EXISTS {test_table_name}_uniq_idx
            ON {test_table_name} (
                program,
                date_added,
                url,
                status,
                term,
                degree
            )
            """
        )

    db_connection.commit()

    try:
        yield test_table_name
    finally:
        with db_connection.cursor() as cur:
            cur.execute(f"DROP TABLE IF EXISTS {test_table_name}")
        db_connection.commit()

def _completed_process(returncode=0, stdout="", stderr=""):
    """Build a fake subprocess result object.

    :param returncode: Simulated process return code.
    :type returncode: int
    :param stdout: Simulated standard output.
    :type stdout: str
    :param stderr: Simulated standard error.
    :type stderr: str
    :return: Object mimicking a subprocess result.
    :rtype: types.SimpleNamespace
    """
    return SimpleNamespace(returncode=returncode, stdout=stdout, stderr=stderr)

def _page_text(html):
    """Return normalized visible text from rendered HTML.

    :param html: HTML document string.
    :type html: str
    :return: Normalized visible page text.
    :rtype: str
    """
    soup = BeautifulSoup(html, "html.parser")
    return " ".join(soup.get_text(" ", strip=True).split())

def _pull_batch_one():
    """Return the first fake scrape batch.

    :return: First batch of raw scraped rows.
    :rtype: list[dict]
    """
    return [
        {
            "Program Name": "Johns Hopkins University Computer Science",
            "Comments": "Accepted with funding",
            "Date of Information Added to Grad Cafe": "January 15, 2026",
            "URL link to applicant entry": "https://example.com/applicant/1",
            "Applicant Status": "Accepted",
            "Semester and Year of Program Start": "Fall 2026",
            "International / American Student": "American",
            "GPA": "3.91",
            "GRE Score": "325",
            "GRE V Score": "160",
            "GRE AW": "4.5",
            "Masters or PhD": "Masters",
            "llm-generated-program": "Computer Science",
            "llm-generated-university": "Johns Hopkins University",
        },
        {
            "Program Name": "MIT Computer Science",
            "Comments": "Accepted after interview",
            "Date of Information Added to Grad Cafe": "January 16, 2026",
            "URL link to applicant entry": "https://example.com/applicant/2",
            "Applicant Status": "Accepted",
            "Semester and Year of Program Start": "Fall 2026",
            "International / American Student": "International",
            "GPA": "3.80",
            "GRE Score": "330",
            "GRE V Score": "162",
            "GRE AW": "5.0",
            "Masters or PhD": "PhD",
            "llm-generated-program": "Computer Science",
            "llm-generated-university": "MIT",
        },
        {
            "Program Name": "Stanford University Computer Science",
            "Comments": "Waitlisted",
            "Date of Information Added to Grad Cafe": "January 17, 2026",
            "URL link to applicant entry": "https://example.com/applicant/3",
            "Applicant Status": "Waitlisted",
            "Semester and Year of Program Start": "Fall 2026",
            "International / American Student": "American",
            "GPA": "3.95",
            "GRE Score": "332",
            "GRE V Score": "165",
            "GRE AW": "5.0",
            "Masters or PhD": "PhD",
            "llm-generated-program": "Computer Science",
            "llm-generated-university": "Stanford University",
        },
    ]

def _pull_batch_two_with_overlap():
    """Return a second fake scrape batch containing overlap plus one new row.

    :return: Second batch of raw scraped rows.
    :rtype: list[dict]
    """
    return [
        {
            "Program Name": "MIT Computer Science",
            "Comments": "Accepted after interview",
            "Date of Information Added to Grad Cafe": "January 16, 2026",
            "URL link to applicant entry": "https://example.com/applicant/2",
            "Applicant Status": "Accepted",
            "Semester and Year of Program Start": "Fall 2026",
            "International / American Student": "International",
            "GPA": "3.80",
            "GRE Score": "330",
            "GRE V Score": "162",
            "GRE AW": "5.0",
            "Masters or PhD": "PhD",
            "llm-generated-program": "Computer Science",
            "llm-generated-university": "MIT",
        },
        {
            "Program Name": "Stanford University Computer Science",
            "Comments": "Waitlisted",
            "Date of Information Added to Grad Cafe": "January 17, 2026",
            "URL link to applicant entry": "https://example.com/applicant/3",
            "Applicant Status": "Waitlisted",
            "Semester and Year of Program Start": "Fall 2026",
            "International / American Student": "American",
            "GPA": "3.95",
            "GRE Score": "332",
            "GRE V Score": "165",
            "GRE AW": "5.0",
            "Masters or PhD": "PhD",
            "llm-generated-program": "Computer Science",
            "llm-generated-university": "Stanford University",
        },
        {
            "Program Name": "Carnegie Mellon University Computer Science",
            "Comments": "Accepted",
            "Date of Information Added to Grad Cafe": "January 18, 2026",
            "URL link to applicant entry": "https://example.com/applicant/4",
            "Applicant Status": "Accepted",
            "Semester and Year of Program Start": "Fall 2026",
            "International / American Student": "International",
            "GPA": "3.88",
            "GRE Score": "328",
            "GRE V Score": "161",
            "GRE AW": "4.5",
            "Masters or PhD": "PhD",
            "llm-generated-program": "Computer Science",
            "llm-generated-university": "Carnegie Mellon University",
        },
    ]

def _load_table_count(connection, table_name):
    """Return the number of rows in the given table.

    :param connection: Live PostgreSQL connection.
    :type connection: psycopg.Connection
    :param table_name: Table name to count.
    :type table_name: str
    :return: Number of rows in the table.
    :rtype: int
    """
    with connection.cursor() as cur:
        cur.execute(f"SELECT COUNT(*) FROM {table_name}")
        return cur.fetchone()[0]

def _make_fake_get_all_query_results(table_name):
    """Build a query-results function backed by the test table.

    This matches your template shape:
    ``Answer: {{ answer[0] }} {{ answer[1] }}``

    :param table_name: Test table to query.
    :type table_name: str
    :return: Function compatible with ``app.get_all_query_results``.
    :rtype: collections.abc.Callable
    """
    def fake_get_all_query_results(connection):
        """Query the test table and return analysis items.

        :param connection: Live PostgreSQL connection supplied by the app.
        :type connection: psycopg.Connection
        :return: Analysis question/answer pairs.
        :rtype: list[tuple[str, tuple[str, object]]]
        """
        with connection.cursor() as cur:
            cur.execute(f"SELECT COUNT(*) FROM {table_name}")
            total_rows = cur.fetchone()[0]

            cur.execute(
                f"""
                SELECT ROUND(
                    AVG(CASE WHEN status ILIKE 'Accepted%%' THEN 1.0 ELSE 0.0 END) * 100,
                    2
                )
                FROM {table_name}
                """
            )
            acceptance_pct = cur.fetchone()[0] or 0

        return [
            ("1) How many records are loaded?", ("Total loaded:", total_rows)),
            ("2) What percent are acceptances?", ("Acceptance rate:", f"{acceptance_pct:.2f}%")),
        ]

    return fake_get_all_query_results

def _install_end_to_end_fakes(app_module, monkeypatch, test_table, scrape_batches):
    """Install fakes needed for end-to-end integration tests.

    :param app_module: Imported Flask app module.
    :type app_module: module
    :param monkeypatch: Pytest monkeypatch fixture.
    :type monkeypatch: pytest.MonkeyPatch
    :param test_table: Test table receiving inserted rows.
    :type test_table: str
    :param scrape_batches: Ordered fake scrape outputs to use per pull.
    :type scrape_batches: list[list[dict]]
    :return: Mutable test state used by the fake pull flow.
    :rtype: dict[str, object]
    """
    state = {
        "pull_count": 0,
        "watermark": None,
        "scrape_batches": scrape_batches,
    }

    def fake_run_python_script(script_path, *args):
        """Fake scrape/clean/update commands and run real DB load.

        :param script_path: Script path the app is attempting to execute.
        :type script_path: pathlib.Path | str
        :param args: Command-line arguments passed to the script.
        :type args: tuple[str, ...]
        :return: Fake process result.
        :rtype: types.SimpleNamespace
        """
        script_path = Path(script_path)

        if script_path == app_module.SCRAPE_SCRIPT:
            batch_index = min(state["pull_count"], len(state["scrape_batches"]) - 1)
            batch = state["scrape_batches"][batch_index]
            state["pull_count"] += 1

            app_module.RAW_JSON_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
            with open(app_module.RAW_JSON_OUTPUT, "w", encoding="utf-8") as f:
                json.dump(batch, f, indent=2)

            return _completed_process(returncode=0, stdout="scraped")

        if script_path == app_module.CLEAN_SCRIPT:
            input_path = Path(args[0])
            output_path = Path(args[1])

            with open(input_path, "r", encoding="utf-8") as src:
                payload = json.load(src)

            output_path.parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, "w", encoding="utf-8") as dst:
                json.dump(payload, dst, indent=2)

            return _completed_process(returncode=0, stdout="cleaned")

        if script_path == app_module.LOAD_SCRIPT:
            args_list = list(args)
            input_path = args_list[args_list.index("--input") + 1]
            delete_date = None
            if "--delete-date" in args_list:
                delete_date = args_list[args_list.index("--delete-date") + 1]

            load_data.load_json_to_postgres(
                json_file=input_path,
                table_name=test_table,
                delete_date=delete_date,
            )
            return _completed_process(returncode=0, stdout="loaded")

        if script_path == app_module.QUERY_SCRIPT:
            return _completed_process(returncode=0, stdout="updated")

        return _completed_process(returncode=1, stderr="unexpected script call")

    monkeypatch.setattr(app_module, "run_python_script", fake_run_python_script)
    monkeypatch.setattr(app_module, "load_watermark", lambda: state["watermark"])
    monkeypatch.setattr(
        app_module,
        "save_watermark",
        lambda value: state.__setitem__("watermark", value),
    )

    monkeypatch.setattr(
    app_module,
    "get_db_connection",
    lambda dbname, user: (
        psycopg.connect(conninfo=os.environ["DATABASE_URL"])
        if os.environ.get("DATABASE_URL")
        else psycopg.connect(dbname="applicant_db", user="postgres")
        ),
    )

    monkeypatch.setattr(
        app_module,
        "get_all_query_results",
        _make_fake_get_all_query_results(test_table),
    )

    return state

def test_end_to_end_pull_update_render_shows_updated_analysis(
    client,
    app_module,
    monkeypatch,
    db_connection,
    managed_test_table,
):
    """Verify the full pull -> update -> render workflow.

    :param client: Flask test client.
    :type client: flask.testing.FlaskClient
    :param app_module: Imported Flask app module.
    :type app_module: module
    :param monkeypatch: Pytest monkeypatch fixture.
    :type monkeypatch: pytest.MonkeyPatch
    :param db_connection: Live PostgreSQL connection.
    :type db_connection: psycopg.Connection
    :param managed_test_table: Test-only table name.
    :type managed_test_table: str
    :return: None
    :rtype: None
    """
    test_table = managed_test_table

    _install_end_to_end_fakes(
        app_module=app_module,
        monkeypatch=monkeypatch,
        test_table=test_table,
        scrape_batches=[_pull_batch_one()],
    )

    assert _load_table_count(db_connection, test_table) == 0

    pull_response = client.post("/pull-data")
    assert pull_response.status_code == 200
    assert pull_response.get_json()["ok"] is True
    assert _load_table_count(db_connection, test_table) == 3

    update_response = client.post("/update-analysis")
    assert update_response.status_code == 200
    assert update_response.get_json()["ok"] is True

    render_response = client.get("/analysis")
    page = render_response.get_data(as_text=True)
    page_text = _page_text(page)

    assert render_response.status_code == 200
    assert "Analysis" in page_text
    assert "Answer:" in page_text
    assert "Total loaded: 3" in page_text
    assert re.search(r"Acceptance rate:\s*66\.67%", page_text)
    assert "66.666" not in page_text

def test_multiple_pulls_with_overlapping_data_follow_uniqueness_policy(
    client,
    app_module,
    monkeypatch,
    db_connection,
    managed_test_table,
):
    """Verify repeated pulls with overlap stay consistent.

    :param client: Flask test client.
    :type client: flask.testing.FlaskClient
    :param app_module: Imported Flask app module.
    :type app_module: module
    :param monkeypatch: Pytest monkeypatch fixture.
    :type monkeypatch: pytest.MonkeyPatch
    :param db_connection: Live PostgreSQL connection.
    :type db_connection: psycopg.Connection
    :param managed_test_table: Test-only table name.
    :type managed_test_table: str
    :return: None
    :rtype: None
    """
    test_table = managed_test_table

    _install_end_to_end_fakes(
        app_module=app_module,
        monkeypatch=monkeypatch,
        test_table=test_table,
        scrape_batches=[_pull_batch_one(), _pull_batch_two_with_overlap()],
    )

    first_pull = client.post("/pull-data")
    assert first_pull.status_code == 200
    assert first_pull.get_json()["ok"] is True
    assert _load_table_count(db_connection, test_table) == 3

    second_pull = client.post("/pull-data")
    assert second_pull.status_code == 200
    assert second_pull.get_json()["ok"] is True
    assert _load_table_count(db_connection, test_table) == 4

    update_response = client.post("/update-analysis")
    assert update_response.status_code == 200
    assert update_response.get_json()["ok"] is True

    render_response = client.get("/analysis")
    page = render_response.get_data(as_text=True)
    page_text = _page_text(page)

    assert render_response.status_code == 200
    assert "Total loaded: 4" in page_text
    assert re.search(r"Acceptance rate:\s*75\.00%", page_text)
