# Start sever and connect to database using psql command line tool -bash
#"/c/Program Files/PostgreSQL/18/bin/pg_ctl.exe" start -D "C:\PostgreSQL\18\data"
#"/c/Program Files/PostgreSQL/18/bin/psql.exe" -U postgres -h localhost -d studentcourses

import psycopg

# Connect to the database we created
connection = psycopg.connect(
    dbname="studentcourses",
    user="postgres"
)

# Open a cursor to perform database operations
with connection.cursor() as cur:

    cur.execute('DROP TABLE IF EXISTS courses;')
    
    cur.execute("""
        CREATE TABLE courses(
            id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT,
            instructor TEXT,
            room_number int
        );
    
    """)

    cur.execute("""
        INSERT INTO courses(id, name, instructor, room_number)
        VALUES (206, 'Intro to Python', 'Joe', 132),
               (256, 'Modern Software Concepts in Python', 'Liv', 133);
    """)

    connection.commit()

cur.close()
connection.close()

# Open a cursor to perform database operations
with connection.cursor() as cur:

    cur.execute('DROP TABLE IF EXISTS courses;')
    