# This script reads a JSON file and loads its contents into a PostgreSQL database.
# ========================================================================================
# Start sever and connect to database using psql command line tool -bash
#"/c/Program Files/PostgreSQL/18/bin/pg_ctl.exe" start -D "C:\PostgreSQL\18\data"
#"/c/Program Files/PostgreSQL/18/bin/psql.exe" -U postgres -h localhost -d studentcourses
# ========================================================================================

import json
import psycopg
from datetime import datetime

#DB connection parameters
DB_CONFIG = {
    "host": "localhost",
    "port": 5432,
    "dbname": "applicant_db",
    "user": "postgres"
}

#File path and table name
JSON_FILE = r"C:\Users\hz98yb\Training_Files\jhu_software_concepts\module_3\module_2\json_files\llm_extend_applicant_data.json"
TABLE_NAME = "applicants"

#Stripping out non-UTF-8 characters from JSON data to avoid encoding issues when inserting into WIN1252 encoded PostgreSQL.
def clean_obj(obj):
    if isinstance(obj, dict):
        return {k: clean_obj(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [clean_obj(v) for v in obj]
    if isinstance(obj, str):
        return obj.encode("cp1252", errors="ignore").decode("cp1252")
    return obj

def parse_float(value):
    if value in (None, ""):
        return None
    try:
        return float(value)
    except (ValueError, TypeError):
        return None

def parse_date(value):
    if value in (None, ""):
        return None
    try:
        return datetime.strptime(value, "%B %d, %Y").date()
    except ValueError:
        return None

def load_json_to_postgres():
    # Read JSON file
    with open(JSON_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    print("Top-level JSON type:", type(data).__name__)

    # Normalize single object -> list
    if isinstance(data, dict):
        if "rows" in data and isinstance(data["rows"], list):
            data = [clean_obj(row) for row in data["rows"]]
        else:
            data = [clean_obj(data)]
    elif isinstance(data, list):
        data = [clean_obj(row) for row in data]
    else:
        raise TypeError("JSON must be a dict or list of dicts")

    print(len(data), "records after cleaning.")
    print("First record keys:", list(data[0].keys()) if data else [])

    #Test on subset or full file:
    limit = len(data)
    data = data[:limit]

    # Connect and insert
    with psycopg.connect(**DB_CONFIG) as connection:

        with connection.cursor() as cur:
            # Create table if needed
            cur.execute(f"""
                CREATE TABLE IF NOT EXISTS {TABLE_NAME} (
                    p_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    program text,
                    comments text,
                    date_added date,
                    url text,
                    status text,
                    term text,
                    us_or_international text,
                    gpa float,
                    gre float,
                    gre_v float,
                    gre_aw float,
                    degree text,
                    llm_generated_program text,
                    llm_generated_university text,
                    loaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """)

            # Insert rows
            rows_to_insert = [
                (
                    row.get("Program Name") or None,
                    row.get("Comments") or None,
                    parse_date(row.get("Date of Information Added to Grad Cafe")),
                    row.get("URL link to applicant entry") or None,
                    row.get("Applicant Status") or None,
                    row.get("Semester and Year of Program Start") or None,
                    row.get("International / American Student") or None,
                    parse_float(row.get("GPA")),
                    parse_float(row.get("GRE Score")),
                    parse_float(row.get("GRE V Score")),
                    parse_float(row.get("GRE AW")),
                    row.get("Masters or PhD") or None,
                    row.get("llm-generated-program") or None,
                    row.get("llm-generated-university") or None
                )
                for row in data
            ]

            cur.executemany(
                f"""
                INSERT INTO {TABLE_NAME} (
                    program,
                    comments,
                    date_added,
                    url,
                    status,
                    term,
                    us_or_international,
                    gpa,
                    gre,
                    gre_v,
                    gre_aw,
                    degree,
                    llm_generated_program,
                    llm_generated_university
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                """,
                rows_to_insert
            )

        #Commit changes
        connection.commit()

        #Close connection
        cur.close()
        connection.close()

    print(f"Inserted {len(data)} rows into {TABLE_NAME}")

if __name__ == "__main__":
    load_json_to_postgres()
